title: Slate theme
url: "http://romerorigger.com"
baseurl: "/projects"
markdown: kramdown
traking_id: #
sass:
    style: compressed
    sass_dir: _sass

description: Slate is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
