# Basic site info
title:              "Aprendiendo •••"
description:        "Rigging Technology & Research"
keywords:           "Autodesk, Maya, Rigging, Rigger, Python, PyMel,API"
logo_text:          "Romero"
show_tagline:       true # edit file in /_includes/tagline.html
show_social_icons:  true # edit file in /_includes/social_links.html
og_locale:          "es_la"
cover:              "/assets/logo.png" # site image cover

# Site URL settings
url:                https://romerorigger.github.io # site url
baseurl:            /microblog # for gh-pages
enforce_ssl:        null
github_post_dir:    https://github.com/romeroRigger/teaching/tree/master/


# Site author info
author:
  name:             "Jaime Romero"
  email:            info@romerorigger.com
  github_username:  romerorigger
  twitter_username: romerorigger
 




# Disqus comment settings
# disqus_enabled:     false
# disqus_shortname:   

# Google Analytics ID
# google_analytics_code:

# Build settings
source:             ./
destination:        ./_site
permalink:          /:year/:title
markdown:           kramdown
highlighter:        rouge
timezone:           America/Colombia
exclude:            ["README.md", "LICENSE.md", "CHANGELOG.md"]

# Site configurations
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           [local]
  blanklines:       false
  profile:          false
  startings:        [html, head, body]

sass:
  sass_dir:         assets/scss
  style:            compressed # expanded

plugins:
  - jekyll-sitemap

theme: jekyll-theme-minimal